load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_shared_library.bzl", "cc_shared_library")

licenses(["notice"])

cc_library(
    name = "bar",
    srcs = ["bar.cc"],
    hdrs = ["bar.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "bar_wrapper",
    visibility = ["//visibility:public"],
    deps = [":bar"],
)

cc_shared_library(
    name = "bar_so",
    exports_filter = select({"//conditions:default": ["@test_repo//:__pkg__"]}),
    tags = ["manual"],
    visibility = ["//visibility:public"],
    deps = [":bar_wrapper"],
)
