# buildifier: disable=bzl-visibility
load(
    "@rules_cc//cc/private/toolchain:unix_cc_toolchain_config.bzl",
    unix_cc_toolchain_config = "cc_toolchain_config",
)

# Macro for calling cc_toolchain_config from @bazel_tools with setting the
# right paths and flags for the tools.
def cc_toolchain_config(
        name,
        abi_libc_version,
        abi_version,
        compile_flags,
        compiler,
        conly_flags,
        coverage_compile_flags,
        coverage_link_flags,
        cpu,
        cxx_builtin_include_directories,
        cxx_flags,
        dbg_compile_flags,
        host_system_name,
        link_flags,
        link_libs,
        opt_compile_flags,
        opt_link_flags,
        supports_start_end_lib,
        target_libc,
        target_system_name,
        tool_paths,
        toolchain_identifier,
        unfiltered_compile_flags,
        extra_features = []):
    unix_cc_toolchain_config(
        name = name,
        abi_libc_version = abi_libc_version,
        abi_version = abi_version,
        archive_flags = [],
        compile_flags = compile_flags,
        compiler = compiler,
        conly_flags = conly_flags,
        coverage_compile_flags = coverage_compile_flags,
        coverage_link_flags = coverage_link_flags,
        cpu = cpu,
        cxx_builtin_include_directories = cxx_builtin_include_directories,
        cxx_flags = cxx_flags,
        dbg_compile_flags = dbg_compile_flags,
        fastbuild_compile_flags = [],
        host_system_name = host_system_name,
        link_flags = link_flags,
        link_libs = link_libs,
        extra_features = extra_features,
        opt_compile_flags = opt_compile_flags,
        opt_link_flags = opt_link_flags,
        supports_start_end_lib = supports_start_end_lib,
        target_libc = target_libc,
        target_system_name = target_system_name,
        tool_paths = tool_paths,
        toolchain_identifier = toolchain_identifier,
        unfiltered_compile_flags = unfiltered_compile_flags,
    )
