load("//cc/toolchains:feature.bzl", "cc_feature")

package(default_visibility = [
    "//cc/toolchains:__subpackages__",
    "//tests:__subpackages__",
])

cc_feature(
    name = "clang",
    feature_name = "compiler_clang",
)

cc_feature(
    name = "clang-cl",
    feature_name = "compiler_clang_cl",
)

cc_feature(
    name = "gcc",
    feature_name = "compiler_gcc",
)

cc_feature(
    name = "mingw-gcc",
    feature_name = "compiler_mingw_gcc",
)

cc_feature(
    name = "msvc-cl",
    feature_name = "compiler_msvc_cl",
)

cc_feature(
    name = "emscripten",
    feature_name = "compiler_emscripten",
)
