cc_test(
    name = "quick_test",
    srcs = ["quick_test.cc"],
    deps = [
        "//dynamic_answer",
        "//static_answer",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
