load("//tests/debug_files:dwo_files_test.bzl","dwo_files_test_suite")



# Call a macro that defines targets that perform the tests at analysis time,
# and that can be executed with "bazel test" to return the result.
dwo_files_test_suite(name = "dwo_files_test")
