load(":cc_binary_configured_target_tests.bzl", "cc_binary_configured_target_tests")
load(":cc_import_configured_target_tests.bzl", "cc_import_configured_target_tests")

cc_binary_configured_target_tests(name = "cc_binary_configured_target_tests")

cc_import_configured_target_tests(name = "cc_import_configured_target_tests")
