load(":cc_binary_configured_target_tests.bzl", "cc_binary_configured_target_tests")
load(":cc_common_test.bzl", "cc_common_tests")
load(":cc_shared_library_interface_test.bzl", "cc_shared_library_interface_tests")

cc_binary_configured_target_tests(name = "cc_binary_configured_target_tests")

cc_common_tests(name = "cc_common_tests")

cc_shared_library_interface_tests(name = "cc_shared_library_interface_tests")
