package(default_visibility = ["//visibility:private"])

filegroup(
    name = "srcs",
    srcs = [
        "BUILD",
        "library_link_args.bzl",
    ],
    visibility = ["//cc/toolchains/args/libraries_to_link:__pkg__"],
)
