load("//cc/toolchains:target_capability.bzl", "cc_target_capability")
load("//cc/toolchains:tool_capability.bzl", "cc_tool_capability")

package(default_visibility = ["//visibility:public"])

cc_tool_capability(
    name = "supports_start_end_lib",
)

cc_tool_capability(
    name = "supports_interface_shared_libraries",
)

cc_target_capability(
    name = "supports_dynamic_linker",
)

cc_target_capability(
    name = "supports_pic",
)
