load("//cc/toolchains:tool_capability.bzl", "cc_tool_capability")

package(default_visibility = ["//visibility:public"])

cc_tool_capability(
    name = "supports_start_end_lib",
)

cc_tool_capability(
    name = "supports_interface_shared_libraries",
)

cc_tool_capability(
    name = "supports_dynamic_linker",
)

cc_tool_capability(
    name = "supports_pic",
)

cc_tool_capability(
    name = "has_configured_linker_path",
)

cc_tool_capability(
    name = "targets_windows",
)

cc_tool_capability(
    name = "copy_dynamic_libraries_to_binary",
)
