load("@rules_shell//shell:sh_test.bzl", "sh_test")

sh_test(
    name = "collect_cc_coverage_test",
    size = "small",
    srcs = ["collect_cc_coverage_test.sh"],
    data = ["collect_cc_coverage.sh"],
    target_compatible_with = ["@platforms//os:linux"],
)

config_setting(
    name = "incompatible_use_native_collect_cc_coverage_enabled",
    flag_values = {
        "//cc/settings:incompatible_use_native_collect_cc_coverage": "true",
    },
)

filegroup(
    name = "collect_cc_coverage",
    srcs = select({
        ":incompatible_use_native_collect_cc_coverage_enabled": ["@bazel_tools//tools/test:collect_cc_coverage"],
        "//conditions:default": ["collect_cc_coverage.sh"],
    }),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "srcs",
    srcs = glob([
        "**",
    ]),
    visibility = ["//visibility:public"],
)
