package(default_visibility = ["//tests/rule_based_toolchain:__subpackages__"])

exports_files(
    glob(
        ["*"],
        exclude = ["BUILD"],
    ),
)

filegroup(
    name = "multiple",
    srcs = [
        "multiple1",
        "multiple2",
    ],
)
