#!/bin/bash
#
# Sample script demonstrating custom C++ toolchain selection: handles
# the command that translates a cc_library's .o (object file) into
# .a (archive).

echo "$0: running sample cc_library linker (produces .a output)."

# https://docs.bazel.build/versions/master/cc-toolchain-config-reference.html
# defines fancier ways to generate custom command lines. This script just shows
# the default, which looks like:
#
# examples/custom_toolchain/sample_linker @bazel-out/x86-fastbuild/bin/examples/custom_toolchain/libbuildme.a-2.params.

for arg in "$@"; do
    if [[ "$arg" == *.a ]]; then
        OUTFILE="$arg"
        break
    fi
done

# if [[ -n "$OUTFILE" ]]; then
#     echo "Output file is: $OUTFILE"
# else
#     echo "No '.a' file found in the arguments."
# fi

echo "kaki = $OUTFILE"

echo "$0: sample output"  >  $OUTFILE
echo "$0: sample output changed"  >  $OUTFILE.change
