#!/bin/bash
#
# Sample script demonstrating custom C++ toolchain selection: handles
# the command that translates a cc_library's .cc (source file) into .o  (object
# file) or the command used to link .o files into the final executable
# (just like gcc is used as a front to the linker).

echo "$0: running sample cc_library compiler (produces .o output)."

# https://docs.bazel.build/versions/master/cc-toolchain-config-reference.html
# defines fancier ways to generate custom command lines. This script just shows
# the default, which looks like:
#
# examples/custom_toolchain/sample_compiler <various compiler flags> -o bazel-out/x86-fastbuild/bin/examples/custom_toolchain/_objs/buildme/buildme.o.

# Get last command-line argument
OUTFILE=${!#}

if [[ "$OUTFILE" == @* ]]; then
    # This means we are creating an executable.

    # Remove leading @ and param file suffix.
    OUTFILE=${OUTFILE#@}
    OUTFILE=${OUTFILE%-*}
    
    # Do not create a .d file
    DOTD_FILE=
else
    # This means we're creating a .o file
    OUTFILE=${OUTFILE}
    DOTD_FILE=${OUTFILE%.o}.d
fi

echo "$0: sample output" > $OUTFILE
echo "$0: sample output changed" > $OUTFILE.change

if [[ -n $DOTD_FILE ]]; then
    echo "sample .d output ($0)" > $DOTD_FILE
fi
